name: Docker Builds & Push
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
env:
  JAVA_VERSION: '11'
  JAVA_DISTRO: 'zulu'

jobs:
  build:
    if: github.repository == 'streamthoughts/kafka-connect-file-pulse'
    name: 'Build Docker Image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1

      - name: 'Set Docker Image Build-Args'
        run: |
          echo "VERSION=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "CREATED=$(date --rfc-3339=seconds)" >> $GITHUB_ENV

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'maven'

      - name: 'Build with Maven'
        run: |
          chmod +x mvnw
          ./mvnw -ntp -B --file pom.xml -Pdist package -DskipTests

      - name: 'Copy distribution'
        run: cp ./connect-file-pulse-plugin/target/components/packages/streamthoughts-kafka-connect-file-pulse-${{ env.VERSION }}.zip ./docker/ \

      - name: 'Login to DockerHub'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build & Push to Docker Hub'
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64
          file: ./docker/Dockerfile
          no-cache: true
          push: true
          tags: streamthoughts/kafka-connect-file-pulse:master
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ env.GIT_COMMIT }}
            BRANCH=${{ env.GIT_BRANCH }}
            CREATED=${{ env.CREATED }}